Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You 
have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 
jobs data. 
This task will be done in following steps
: 
1. First get the webpage https://www.naukri.com/
2. Enter “Data Analyst” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the location” field. 
3. Then click the search button. 
4. Then scrape the data for the first 10 jobs results you get. 
5. Finally create a dataframe of the scraped data.

In [2]:
import selenium
import pandas as pd
from selenium import webdriver

driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")

driver.get('https://www.naukri.com/')

search_job=driver.find_element_by_id('qsb-keyword-sugg')
search_job.send_keys("Data Analyst")

search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
search_loc.send_keys("Bangalore")

search_btn=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_btn.click()

url1="https://www.naukri.com/data-analyst-jobs-in-bangalore?k=data%20analyst&l=bangalore"

driver.get(url1)


job_titles=[]
company_names=[]
locations_list=[]
experiences_list=[]


titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags[0:4]

for i in titles_tags:
    title=i.text
    job_titles.append(title)
job_titles[0:4]


companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags[0:4]

for i in companies_tags:
    company_name=i.text
    company_names.append(company_name)
company_names[0:4]


locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
locations_tags[0:4]

for i in locations_tags:
    locations=i.text
    locations_list.append(locations)
locations_list[0:4]


experiences_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
experiences_tags[0:4]

for i in experiences_tags:
    experience=i.text
    experiences_list.append(experience)
experiences_list[0:4]


(len(job_titles),len(company_names),len(locations_list),len(experiences_list))


jobs=pd.DataFrame({})
jobs['Job_title']=job_titles[0:10]
jobs['Company_name']=company_names[0:10]
jobs['Job_location']=locations_list[0:10]
jobs['Experience_required']=experiences_list[0:10]

jobs

<ipython-input-2-8a803689ab46>:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")
<ipython-input-2-8a803689ab46>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_job=driver.find_element_by_id('qsb-keyword-sugg')
<ipython-input-2-8a803689ab46>:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
<ipython-input-2-8a803689ab46>:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_btn=driver.find_element_by_xpath("//div[@class='search-btn']/button")
<ipython-input-2-8a803689ab46>:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
<ipython-input-2-8a803689ab46>:38: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
<ipython-input-2-8a803689ab46>:47: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
<ipython-input-2-8a803689ab46>:56: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  experiences_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")

,Job_title,Company_name,Job_location,Experience_required
0,Senior Business Data Analyst,Tech Data Advanced Solutions India Pvt Ltd,"Bangalore/Bengaluru, Mumbai (All Areas)",3-8 Yrs
1,Data Analyst - Flipkart Analytics,Flipkart,Bangalore/Bengaluru(Bellandur),0-3 Yrs
2,Business Data Analyst - Database Design/Mining,AugmatrixGo,Bangalore/Bengaluru,2-5 Yrs
3,Urgent Openings For Data Analyst / Business An...,Flipkart,Bangalore/Bengaluru,1-6 Yrs
4,Data Analyst,Rupeek Fintech Pvt Ltd,Bangalore/Bengaluru,0-2 Yrs
5,Business Data Analyst(BigId) - Capco - Bangalore,Capco Technologies Pvt Ltd,Bangalore/Bengaluru,3-8 Yrs
6,Data Analyst,CINDREBAY SCHOOL OF FASHION & INTERIOR DESIGN,"Kochi/Cochin, Cannanore/Kannur, Nagpur, Calicu...",1-4 Yrs
7,Senior Data Analyst,Pioneer Business Solutions,Bangalore/Bengaluru,6-11 Yrs
8,Senior Data Analyst,Advanced Computer Software,Bangalore/Bengaluru,3-5 Yrs
9,Sr Data Analyst,Pioneer Business Solutions,Bangalore/Bengaluru,3-8 Yrs

Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You 
have to scrape the job-title, job-location, company_name. You have to scrape first 10 jobs data. 
This task will be done in following steps: 
1. First get the webpage https://www.naukri.com/ 2. Enter “Data Scientist” in “Skill, Designations, Companies” field and enter “Bangalore” in “enter the 
location” field. 
3. Then click the search button. 
4. Then scrape the data for the first 10 jobs results you get. 
5. Finally create a dataframe of the scraped data.

In [4]:
import selenium
import pandas as pd
from selenium import webdriver

driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")

driver.get('https://www.naukri.com/')

search_job=driver.find_element_by_id('qsb-keyword-sugg')
search_job.send_keys("Data Scientist")
search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
search_loc.send_keys("Bangalore/Bengaluru")



url2="https://www.naukri.com/data-scientist-jobs-in-bangalore-bengaluru?k=data%20scientist&l=bangalore%2Fbengaluru"

driver.get(url2)

job_titles=[]
company_names=[]
locations_list=[]


titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags[0:4]

for i in titles_tags:
    title=i.text
    job_titles.append(title)
job_titles[0:4]

companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags[0:4]


for i in companies_tags:
    company_name=i.text
    company_names.append(company_name)
company_names[0:4]


locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
locations_tags[0:4]

for i in locations_tags:
    locations=i.text
    locations_list.append(locations)
locations_list[0:4]

(len(job_titles),len(company_names),len(locations_list))

jobs=pd.DataFrame({})
jobs['job_title']=job_titles[0:10]
jobs['company_name']=company_names[0:10]
jobs['job_location']=locations_list[0:10]

jobs

<ipython-input-4-0418291fbb72>:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")
<ipython-input-4-0418291fbb72>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_job=driver.find_element_by_id('qsb-keyword-sugg')
<ipython-input-4-0418291fbb72>:11: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
<ipython-input-4-0418291fbb72>:25: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
<ipython-input-4-0418291fbb72>:33: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
<ipython-input-4-0418291fbb72>:43: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")

,job_title,company_name,job_location
0,Data Scientist: Advanced Analytics,IBM India Pvt. Limited,Bangalore/Bengaluru
1,Senior Data Scientist,Hitachi Ltd.,Bangalore/Bengaluru
2,Forecasting Analyst/ Data Scientist (US Client),Concentrix Daksh Services,"Gurgaon/Gurugram, Bangalore/Bengaluru"
3,Data Scientist,Toppr,"Hyderabad/Secunderabad, Bangalore/Bengaluru, M..."
4,Process Innovation Analyst - APAC/Data Scienti...,Bayer,"Bangalore/Bengaluru, Hyderabad"
5,Data Scientist,Hitachi Ltd.,Bangalore/Bengaluru
6,Data Scientist,Mobiotics IT Solution Pvt Ltd,Bangalore/Bengaluru(HSR Layout)
7,Data Scientist,Hitachi Ltd.,Bangalore/Bengaluru
8,Senior Data Scientist,Bigshyft Hiring for PayTM (One97 Communications),Bangalore/Bengaluru
9,Data Scientist: Artificial Intelligence,IBM India Pvt. Limited,Bangalore/Bengaluru

Q3: In this question you have to scrape data using the filters available on the webpage as shown below:
You have to use the location and salary filter. 
You have to scrape data for “Data Scientist” designation for first 10 job results. 
You have to scrape the job-title, job-location, company name, experience required. 
The location filter to be used is “Delhi/NCR” The salary filter to be used is “3-6” lakhs 
The task will be done as shown in the below steps: 
1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, and Companies” field. 
3. Then click the search button. 
4. Then apply the location filter and salary filter by checking the respective boxes 
5. Then scrape the data for the first 10 jobs results you get. 
6. Finally create a dataframe of the scraped data.

In [12]:
import selenium
import pandas as pd
from selenium import webdriver

driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")

driver.get('https://www.naukri.com/')


search_job=driver.find_element_by_id('qsb-keyword-sugg')
search_job.send_keys("Data Scientist")

search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
search_loc.send_keys("Delhi")

search_btn=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_btn.click()

#apply filter for location
select_location = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[3]/div[2]/div[2]/label/p/span[1]')
select_location.click()

#apply filter for salary
select_salary = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[4]/div[2]/div[2]/label/p/span[1]')
select_salary.click()

<ipython-input-12-0e77b7692ea7>:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\HP\Downloads\chromedriver_win32/chromedriver.exe")
<ipython-input-12-0e77b7692ea7>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_job=driver.find_element_by_id('qsb-keyword-sugg')
<ipython-input-12-0e77b7692ea7>:13: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_loc=driver.find_element_by_xpath("//input[@id='qsb-location-sugg']")
<ipython-input-12-0e77b7692ea7>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search_btn=driver.find_element_by_xpath("//div[@class='search-btn']/button")

In [20]:
url3="https://www.naukri.com/data-scientist-jobs-in-delhi?k=data%20scientist&l=delhi&cityTypeGid=9508&ctcFilter=3to6"

driver.get(url3)

job_titles=[]
company_names=[]
locations_list=[]


titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles_tags[0:4]

for i in titles_tags:
    title=i.text
    job_titles.append(title)
job_titles[0:4]

companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies_tags[0:4]


for i in companies_tags:
    company_name=i.text
    company_names.append(company_name)
company_names[0:4]


locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
locations_tags[0:4]

for i in locations_tags:
    locations=i.text
    locations_list.append(locations)
locations_list[0:4]

(len(job_titles),len(company_names),len(locations_list))

jobs=pd.DataFrame({})
jobs['titles']=job_titles[0:10]
jobs['company']=company_names[0:10]
jobs['location']=locations_list[0:10]

jobs

<ipython-input-20-795f201b3050>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  titles_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
<ipython-input-20-795f201b3050>:18: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  companies_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
<ipython-input-20-795f201b3050>:28: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  locations_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")

,titles,company,location
0,Data Scientist - Insurance,Huquo Consulting Pvt. Ltd,"Noida, Gurgaon/Gurugram"
1,Job Opportunity || Data Scientist || HCL Techn...,HCL Technologies,Delhi / NCR
2,Data Scientist,ThinkBumblebee Analytics Pvt. Ltd.,"Pune, Bangalore/Bengaluru, Delhi / NCR"
3,Data Scientist III-2,Concentrix Daksh Services,Gurgaon/Gurugram
4,Data Scientist,MoMagic Technologies Pvt. Ltd.,Noida(Sector-126 Noida)
5,Data Scientist,MoMagic Technologies Pvt. Ltd.,Noida(Sector-126 Noida)
6,Urgent Hiring || Data Scientist || Delhi,Shriram Automall India Limited,Delhi / NCR
7,Data Scientist,Optum Global Solutions (India) Private Limited,"Noida, Gurgaon/Gurugram"
8,Data Scientist,Think i,"Kochi/Cochin, Kolkata, Hyderabad/Secunderabad,..."
9,Project Manager | Team Leader | Senior Data Sc...,Tidyquant (OPC) Private Limited,Remote